on:
  workflow_dispatch:
  push:
    branches: main

name: Render and Publish docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install -- upgrade pip
          pip install -e .[docs]
      
      # Manually call quartodoc build
      - name: quartodoc build
        run: |
          quartodoc build

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}