# Team Project Reflection

[.qmd copy of this file to edit](https://github.ubc.ca/mds-2025-26/DSCI_524_collab-sw-dev_students/blob/master/release/team_work/team_work.qmd)

The purpose of this individual report
is to give you an avenue to present your viewpoint
as to how the project went,
how the group worked together,
and your role in the group.

There are two parts, serving different purposes. The first, Teamwork Analysis, is to demonstrate some engagement with github project analytics. 

Another, Teamwork reflection, provides individual evaluation and can be used to adjust final grades of individuals, if needed.

Each group member must complete this form
to report on the contributions of **yourself** and the other group members.

This is a private report,
meaning that none of your classmates will see your submission.

## Teamwork Analysis

You might find [notes on retrospectives](/section2/l8-retrospective.qmd) useful for this part.

In 3-5 paragraphs and referring to you GitHub Projects reports, views and charts (inlude links or screenshots), tell us what did you learn about your project work in this course.

For example, you can comment on 

- how did planning worked for you and was adjusted in the course of the project
- about team velocity changes across milestones, e.g., if M2 (writing code) have significantly more issues than M3 (github actions)?
- did you need more commits to make actions right than source code thanks to debugging?  
- did you end up having a lot of items left in "Todo" at the end of milestones (over-committing)?
- were there any bottlenecks?

Lastly, you can comment on 2-3 things you would change if you were to set up your project again knowing what you know today. It can be organizational (teamwork contract / contributing.md), tool or infrastructural changes (another development flow, rules, particular github action setup, branch protection, ...)

## Teamwork Reflection

For each of the sections below,
evaluate each member of your group by writing the number
that best reflects the extent to which they participated,
prepared, helped the group excel, and was a team player.
Use the following ratings:

| Rating | Description                             |
|--------|-----------------------------------------|
| 4      | Usually (over 90% of the time)          |
| 3      | Frequently (more often than not)        |
| 2      | Sometimes (less than half the time)     |
| 1      | Rarely (never or once in a great while) |


## 1. Preparation

- Prepared for group meetings and presentations
- Spent time becoming familiar with the material relevant for the project
- Understands the project's goal and expectations
- Does what they say they will do on time
- Attends and is on time to group meetings and presentations

| Group member name | Preparation rating |
|-------------------|--------------------|
|                   |                    |
|                   |                    |
|                   |                    |

## 2. Participation & communication

- Articulates ideas effectively when speaking or writing
- Work is without grammatical errors
- Listens to others
- Encourages others to talk

| Group member name | Participation & communication rating |
|-------------------|--------------------------------------|
|                   |                                      |
|                   |                                      |
|                   |                                      |

## 3. Helps group excel

- Expresses great interest in group success by evaluating ideas and suggestions
- Initiates problem solving
- Influences and encourages others to set up high standards
- Doesn't accept just any idea but looks for the best ideas
- Stays motivated from beginning to end of project

| Group member name | Helps group excel rating |
|-------------------|--------------------------|
|                   |                          |
|                   |                          |
|                   |                          |

## 4. Team player (cooperation)

- Knows when to be a leader and a follower
- Keeps an open mind
- Compromises when appropriate
- Can take criticism
- Respects others

| Group member name | Team player (cooperation) rating |
|-------------------|----------------------------------|
|                   |                                  |
|                   |                                  |
|                   |                                  |

Below,
briefly describe the specific contributions each team member
made to your project (**including yourself**).
Point form is fine.
Specifically,
comment on the following areas:

- How the team worked together as a whole, including:
    - What was your role in the group?
      That is, what sort of things did you do to contribute to the evolution of the project?
    - What were the roles of others in your group?
- What went well and poorly throughout the team project experience?

## Submission instructions

- Copey the document as `.qmd` or `.md`, edit, convert to pdf and submit to gradescope.